---
- name: "SECTION | 2.1 | Special Purpose Services"
  include_tasks: cis_2.1.x.yml
  tags:
    - always

- name: "SECTION | 2.2 | Service Clients"
  include_tasks: cis_2.2.x.yml
  tags:
    - always

- name: "SECTION | 2.3 | Ensure nonessential services are removed or masked"
  include_tasks: cis_2.3.yml
  tags:
    - always
